// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpVNFfefPAosr1_eGYyWDh043XYLmg1GI',
    appId: '1:389746513618:web:87154f30f704f1f2b5ff0b',
    messagingSenderId: '389746513618',
    projectId: 'abaca-thesis',
    authDomain: 'abaca-thesis.firebaseapp.com',
    storageBucket: 'abaca-thesis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CBNdV2qNkvKS2JJGYvlZLM6sJK1qJDU',
    appId: '1:389746513618:android:e53e8bbe531b8829b5ff0b',
    messagingSenderId: '389746513618',
    projectId: 'abaca-thesis',
    storageBucket: 'abaca-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAIQztQ440BtlN9kPFbYejfT0KrwWvY0U',
    appId: '1:389746513618:ios:161ebfc9beeb8d86b5ff0b',
    messagingSenderId: '389746513618',
    projectId: 'abaca-thesis',
    storageBucket: 'abaca-thesis.appspot.com',
    iosBundleId: 'com.example.abacaClassification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAIQztQ440BtlN9kPFbYejfT0KrwWvY0U',
    appId: '1:389746513618:ios:ba1a8a38cab6a1d9b5ff0b',
    messagingSenderId: '389746513618',
    projectId: 'abaca-thesis',
    storageBucket: 'abaca-thesis.appspot.com',
    iosBundleId: 'com.example.abacaClassification.RunnerTests',
  );
}
